Controller:
  setpoint: 0
  stimulation_amplitude: 0.1
  stimulation_frequency: 40.0
  ts: 0.02
Simulation:
  Controller: OPEN
  DBS_stimulation: false
  RandomSeed: 6707
  RunTime: 10000.0
  SteadyStateDuration: 6000
  ctx_stimulation: true
  save_ctx_lfp: true
  save_ctx_voltage: true
