---
# Simulation
Controller: PID
Modulation: amplitude
RunTime: 4000.0
SteadyStateDuration: 500
save_ctx_voltage: True
save_ctx_lfp: True

# Controller
setpoint: 1.0414e-04
kp: 0.23
ti: 0.2
td: 0
ts: 0.02
min_value: 0.0
max_value: 3.0
