---
# Simulation
Controller: OPEN
RunTime: 4000.0
SteadyStateDuration: 500
ctx_stimulation: True
DBS_stimulation: False
save_ctx_voltage: True
save_ctx_lfp: True

# Controller
setpoint: 0
ts: 0.02
stimulation_amplitude: 0.5
