---
# Simulation
Controller: OPEN
RunTime: 2000.0
SteadyStateDuration: 500
ctx_stimulation: True
DBS_stimulation: False
save_ctx_voltage: True
save_ctx_lfp: True
create_new_network: True
Pop_size: 100

# Controller
setpoint: 0
ts: 0.02
stimulation_amplitude: 2.0
